import './styles/globals.css'
import { Lato } from 'next/font/google'
 
const lato = Lato({
  weight: ['300','400','700','900'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
        <body className={`text-dark-blue ${lato.className}`}>
          {children}
        </body>
    </html>
  )
}
